version: "3.7"

services:
    db:
        image: postgres
        volumes:
            - dockerapp-postgres-data:/var/lib/postgres
            - ./sql_sample:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: test 
            POSTGRES_DB: dockerapp

    solr:
        image: solr:8.6
        ports:
            - 8983:8983   

    web:
        image: tomcat:8.5.41-jre8-alpine
        volumes:
            - ./dist/sample.war:/usr/local/tomcat/webapps/sample.war
        ports:
            - 8080:8080


volumes:
    dockerapp-postgres-data:
    schema.sql: